package model;

public enum BestellingsEvents {
    START_NIEUWE_BESTELLING,
    VOEG_BESTELLIJN_TOE,
    VOEG_BELEG_TOE,
    VOEG_IDENTIEKE_BESTELLING_TOE,
    VERWIJDER_BESTELLIJN,
    ANNULLEER;
}
